variant = "loose"

[[issues]]
file = "app/Actions/Fortify/CreateNewUser.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Actions/Fortify/ResetUserPassword.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Concerns/PasswordValidationRules.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Concerns/ProfileValidationRules.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Controllers/Controller.php"
code = "no-empty-comment"
message = "Empty comments are not allowed."
count = 1

[[issues]]
file = "app/Http/Controllers/Controller.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Controllers/Settings/ProfileController.php"
code = "final-controller"
message = "Controller classes should be declared as `final`."
count = 1

[[issues]]
file = "app/Http/Controllers/Settings/ProfileController.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Controllers/Settings/SecurityController.php"
code = "final-controller"
message = "Controller classes should be declared as `final`."
count = 1

[[issues]]
file = "app/Http/Controllers/Settings/SecurityController.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Middleware/HandleAppearance.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Middleware/HandleInertiaRequests.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Requests/Settings/PasswordUpdateRequest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Requests/Settings/ProfileDeleteRequest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Requests/Settings/ProfileUpdateRequest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Http/Requests/Settings/TwoFactorAuthenticationRequest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Models/User.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "app/Models/User.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Providers/AppServiceProvider.php"
code = "no-empty-comment"
message = "Empty comments are not allowed."
count = 1

[[issues]]
file = "app/Providers/AppServiceProvider.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 1

[[issues]]
file = "app/Providers/AppServiceProvider.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "app/Providers/FortifyServiceProvider.php"
code = "no-empty-comment"
message = "Empty comments are not allowed."
count = 1

[[issues]]
file = "app/Providers/FortifyServiceProvider.php"
code = "prefer-arrow-function"
message = "This closure can be simplified to a more concise arrow function."
count = 1

[[issues]]
file = "app/Providers/FortifyServiceProvider.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 7

[[issues]]
file = "app/Providers/FortifyServiceProvider.php"
code = "prefer-static-closure"
message = "This closure does not use `$this` and should be declared static."
count = 2

[[issues]]
file = "app/Providers/FortifyServiceProvider.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "database/factories/UserFactory.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 2

[[issues]]
file = "database/factories/UserFactory.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "database/seeders/DatabaseSeeder.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/AuthenticationTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 4

[[issues]]
file = "tests/Feature/Auth/AuthenticationTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/EmailVerificationTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 4

[[issues]]
file = "tests/Feature/Auth/EmailVerificationTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/PasswordConfirmationTest.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 1

[[issues]]
file = "tests/Feature/Auth/PasswordConfirmationTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/PasswordResetTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 3

[[issues]]
file = "tests/Feature/Auth/PasswordResetTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/RegistrationTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "tests/Feature/Auth/RegistrationTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/TwoFactorChallengeTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "tests/Feature/Auth/TwoFactorChallengeTest.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 1

[[issues]]
file = "tests/Feature/Auth/TwoFactorChallengeTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Auth/VerificationNotificationTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/DashboardTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/ExampleTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Settings/ProfileUpdateTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 6

[[issues]]
file = "tests/Feature/Settings/ProfileUpdateTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 2

[[issues]]
file = "tests/Feature/Settings/ProfileUpdateTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Feature/Settings/SecurityTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 1

[[issues]]
file = "tests/Feature/Settings/SecurityTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 4

[[issues]]
file = "tests/Feature/Settings/SecurityTest.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 3

[[issues]]
file = "tests/Feature/Settings/SecurityTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/TestCase.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/Unit/ExampleTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 1

[[issues]]
file = "tests/Unit/ExampleTest.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1
